# Site settings
title: 試行錯誤を繰り返すブログ@GitHub Pages
email: 
description: >- # this means to ignore newlines until "baseurl:"
  購入したデバイスのレビューや、PC、スマートフォンの不具合対処方法、
  Python や機械学習での試行錯誤をメモしていきます。 
  ただし、解決方法は金銭的な負担が生じないモノを優先で。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pokotenote.com/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - webrick
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Theme Settings
minimal_mistakes_skin    : "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale                   : "ja-JP"
repository               : "android-pokoten/android-pokoten.github.io"
words_per_minute         : 100
enable_copy_code_button  : true

# Analytics
analytics:
  provider         : "google-gtag"
  google:
    tracking_id    : G-5MJJTPQXS8

# Site Author
author:
  name             : "Pokoten"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "購入したデバイスのレビューや、PC、スマートフォンの不具合対処方法、Python や機械学習での試行錯誤をメモしていきます。ただし、解決方法は金銭的な負担が生じないモノを優先で。"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/android-pokoten/android-pokoten.github.io" 
    - label: "X"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://x.com/aquamarine02"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 7

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
