# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 試行錯誤を繰り返すブログ@GitHub Pages
email: 
description: >- # this means to ignore newlines until "baseurl:"
  購入したデバイスのレビューや、PC、スマートフォンの不具合対処方法、
  Python や機械学習での試行錯誤をメモしていきます。 
  ただし、解決方法は金銭的な負担が生じないモノを優先で。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pokotenote.com/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
#theme: minima
#theme: jekyll-theme-minimal
plugins:
  - webrick
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: jekyll/minima
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/cayman

google_analytics: G-5MJJTPQXS8

minima:
  skin: solarized
  date_format: "%Y/%m/%d"
  social_links:
  - { platform: github,         user_url: "https://github.com/android-pokoten/android-pokoten.github.io" }
  - { platform: x,              user_url: "https://x.com/aquamarine02" }
  - { platform: youtube,        user_url: "http://www.youtube.com/mabireci" }

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 7
